### ISSUE TITLE
Possible revision to work as switch, selectable USB/Sun input, 2 Sun outputs?

### ISSUE THREAD

**Issue by trguhq** [jgilje/USB2Sun#1]
What I am envisioning is allowing simultaneously allowing either of 2 Sun outputs to select from a USB input or a Sun input.

The reason I wanted this is twofold, I would like a keyboard/mouse switch for two Suns, and I would also like to be able to use a small wireless keyboard with a USB dongle with them at any given time.

So each output would have a button/LED combo for either Sun input or USB input. Selecting either input on a given output could toggle it off on the other output, and toggle off the other input on that output as well (or leave it on?). I was thinking blue LED to stand for USB, and Sun could be yellow for "sun" or any color. Four total buttons and LEDs.

Could be an opportunity to add a power button as well since there would be buttons in this design. Perhaps with LEDs showing power to either Sun output (indicating computer is on)?

**Comment by jgilje** [comment]
So... the short version is a simple no. Unfortunately :disappointed: 

The issue is that the Pico, which I've based this project on, only has two UARTs. And both are in use to to drive the keyboard and mouse on the Sun side of the converter. Leaving no UARTs to drive a signal to the second Sun machine your envisioning here.

Furthermore, to build a full matrix solution like what your envisioning, you'd probably have to get a electronics person involved. I'm not. I'm able to do the simple electronics like the solution is now, but I'm at my limit here :smile: 

You could build two of the boards in this project and add a KVM switch like an Aten CS82U/CS84U (I'm using one myself with this board) to drive multiple Sun machines from a single USB keyboard.

**Comment by trguhq** [comment]
Hmm ok. Picos are cheap enough that using two wouldn't be much of a concern. There might be a more appropriate microcontroller though. I guess it would take 6 UARTs since there would be a Sun input as well? Maybe just an external quad UART I2C/SPI chip?

As far as the electronics, I don't have much expertise in it either, but what I described is pretty simple in that regard as far as I understand. I know how to wire buttons and LEDs. The level shifters seem pretty straight forward. Both inputs would feed into the theoretical microcontroller, and both outputs come from it, and it would handle the multiplexing (the right term?).

I guess the bigger question is whether it is worth pursuing such a niche idea for the small audience of people who might use it. As you say, for someone who wants to use only a USB keyboard and mouse input, combining two of your design with a USB switch would work fine.

Thanks for your thoughts on this.

**Comment by trguhq** [comment]
What I'm thinking now is that one I2C quad (or dual) UART could be one input or output, and the microcontroller could have drivers for them. The firmware could be just a generic system for multiplexing the drivers.

So one could pair a Sun output and an SGI output with a Sun input and a USB input, or more complicated variants, and just configure the core software for that based on the generic drivers? Does that seem like a reasonable idea?

**Comment by jgilje** [comment]
Sorry, forgot to reply. As I said, I don't have the skills here. Please supply some drawings and wiring if you can :)

**Comment by vvuk** [comment]
(Random driveby comment -- thanks for this project, exactly what I was looking for to get some new sparcstations rescued from salvage going!)

A simpler version of this could just use the two UARTs on the pico, but switch at the shifter level.  I am currently about to try a version of this project (thanks!) using a single TXS0108E bidirectional level shifter.  It has an OE enable pin for the entire chip -- so you could theoretically do as many TSX0108Es as you want, and just enable only the chip going to whatever output computer you want triggered by additional GPIO pins on your microcontroller.

**Comment by jgilje** [comment]
That's a great suggestion! Please do follow up with progress updates on your build! :smiley:

**Comment by vvuk** [comment]
Quick update -- the TXS0108E is.. not good :X its internal bidirectional logic (deciding which side is input vs output) is getting very confused by the Sun and/or the rp2040.  I tried bumping the drive strength on the rp2040 side in case that was the issue (2mA min to overcome internal pulldowns on the TXS0108E) but didn't help.

However, I didn't need to go that fancy; a simple MOSFET shifter like https://www.amazon.com/gp/product/B08BZ5X8XH (or any of a million clones like it) works great!

**Comment by trguhq** [comment]
> However, I didn't need to go that fancy; a simple MOSFET shifter like https://www.amazon.com/gp/product/B08BZ5X8XH (or any of a million clones like it) works great!

Are there any boards like that with additional MOSFETs for enabling/disabling the supply voltage or some easy way to do that with GPIO pins without additional transistors?

**Comment by jgilje** [comment]
@vvuk looking at the pinouts, you didn't get an OE-function using the MOSFET shifter you linked?
