### ISSUE TITLE
Should there be a warning not to connect the device to both a Sun and a PC at the same time?

### ISSUE THREAD

**Issue by trguhq** [jgilje/USB2Sun#2]
Since VBUS is connected directly to the USB's power pin, is there some danger of backfeeding from connecting both a Sun and PC to it at the same time (e.g. for flashing)?

Also makes me wonder how many mA is safe to draw from the Sun's keyboard port (thinking for my own revisions to this design).

**Comment by jgilje** [comment]
1. VBUS backfeeding: I don't know, I've never thought about it. In my case, I'm flashing using another Raspberry Pi using the SWD lines. And the USB is used in host mode connected directly to a USB device.
2. I've not read into it. I know the native keyboards also embeds a microcontroller, so some mA is available. I've just assumed it would be enough to drive the Pico as well as a USB keyboard and mouse. And that part has worked for me on my SparcStation4. In my actual setup, the Pico is in turn connected to an Aten KVM switch - and in that setup I need to provide additional power to the KVM switch.

If - based on these answers you would assume I'm not a hardware guy, you'd be absolutely correct :smile: I do love getting feedback on any improved designs from you and others, but as I've mentioned before, I won't be able to turn a suggestion into an implementation hardware-wise.
