### ISSUE TITLE
How does the USB keyboard and mouse connect?

### ISSUE THREAD

**Issue by thetechconspiracy** [jgilje/USB2Sun#3]
Are you supposed to use an OTG adapter and USB hub plugged into the microUSB on the Pico?

Also, does the project require both a USB keyboard and mouse, or can it be used solely with a USB mouse, plugging into a Sun keyboard?

**Comment by jgilje** [comment]
Yeah, you at least need a OTG adapter, and then it depends of course. I have some wireless dongles which present both keyboard and mouse HID-s, I have a KVM switch which also does that. And if not, you're going to have to use a HUB.

I haven't tried the only-mouse option connected to a Sun keyboard before. It should work, I believe the pins are just passed through. If there should be any problems, it would have to be that the USB2Sun adapter configures the keyboard pins unconditionally and may interfere. In that case, maybe it would have been best to setup the keyboard serials lines and mouse line when the corresponding USB device is actually detected.

In addition, I have it currently setup to autoreboot if a keyboard can't be found, if the USB enumeration somehow fails.
